name: build

on:
  # Trigger the workflow on push or pull request to main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Set up operating system
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2

    # Set up Python 3.9
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - uses: snok/install-poetry@v1

    - name: Install package
      run: poetry install

    - name: Check style
      run: poetry run flake8 --exclude=docs*

    - name: Test with pytest
      run: poetry run pytest tests/ --cov=airpyllution --cov-report=xml

# Uncomment once codecov is set up
#     - name: Upload coverage to Codecov  
#     - uses: codecov/codecov-action@v2
#       with:
#         files: ./coverage.xml   # coverage report
#         fail_ci_if_error: true  

#     - name: Build documentation
#       run: poetry run make html --directory docs/
