name: ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest
    steps:
    # Set up Python 3.9
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - uses: actions/checkout@v2

    - uses: snok/install-poetry@v1

    - name: Install package
      run: poetry install

    - name: Test with pytest
      run: poetry run pytest tests/ --cov=airpyllution --cov-report=xml

#     - uses: codecov/codecov-action@v2
#       with:
#         files: ./coverage.xml   # coverage report
#         fail_ci_if_error: true  

#     - name: Build documentation
#       run: poetry run make html --directory docs/
#   cd:
#     # Only run this job if the "ci" job passes
#     needs: ci
#     # Only run this job if new work is pushed to "main"
#     if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#     # Step 1. Set up operating system
#     runs-on: ubuntu-latest
#     steps:
#     # Step 2. Set up Python 3.9
#     - uses: actions/setup-python@v2
#       with:
#         python-version: 3.9
#     # Step 3. Check-out repository so we can access its contents
#     - uses: actions/checkout@v2
#       with:
#         fetch-depth: 0
#     # Step 4. Use PSR to make release
#     - name: Python Semantic Release
#       run: |
#           pip install python-semantic-release
#           git config user.name github-actions
#           git config user.email github-actions@github.com
#           semantic-release publish
#     # Step 5. Publish to TestPyPI
#     - uses: pypa/gh-action-pypi-publish@release/v1
#       with:
#         user: __token__
#         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
#         repository_url: https://test.pypi.org/legacy/
#         skip_existing: true
#     # Step 6. Test install from TestPyPI
#     - name: Test install from TestPyPI
#       run: |
#           pip install \
#           --index-url https://test.pypi.org/simple/ \
#           --extra-index-url https://pypi.org/simple \
#           airpyllution
#     # Step 7. Publish to PyPI
#     - uses: pypa/gh-action-pypi-publish@release/v1
#       with:
#         user: __token__
#         password: ${{ secrets.PYPI_API_TOKEN }}
#         skip_existing: true
